// this file was automatically generated by ModelKit. It must not be modified manually!

#import <JSONModel/JSONModel.h>

extern NSString *const Find_Index;
extern NSString *const Home_Index;
extern NSString *const Search_Index;

@protocol AFFGoodItem @end

NSDictionary *methodMap();

@interface AFFBaseApi : JSONModel @end

@interface AFFPictureItem : AFFBaseApi
@property(nonatomic, assign) NSInteger height; //
@property(nonatomic, copy  ) NSString *url; //
@property(nonatomic, assign) NSInteger width; //
@end

@interface AFFGoodItem : AFFBaseApi
@property(nonatomic, assign) NSInteger mapToId; //id
@property(nonatomic, copy  ) NSString *intro; //
@property(nonatomic, strong) AFFPictureItem *picture; //
@property(nonatomic, copy  ) NSString *title; //问题标题/标题字段
@end

@interface AFFFindIndex : AFFBaseApi
@property(nonatomic, copy  ) NSArray<AFFGoodItem> *list; //
@end

@interface AFFHomeIndex : AFFBaseApi
@property(nonatomic, copy  ) NSArray<AFFGoodItem> *list; //
@end

@interface AFFSearchIndex : AFFBaseApi
@property(nonatomic, copy  ) NSArray<AFFGoodItem> *list; //
@end


