// this file was automatically generated by ModelKit. It must not be modified manually!

#import "AFFApiInterface.h"

NSString *const Find_Index = @"find/index";
NSString *const Home_Index = @"home/index";
NSString *const Search_Index = @"search/index";

static NSDictionary * _method = nil;
NSDictionary *methodMap() {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _method = @{
        Find_Index : @"GET",
        Home_Index : @"GET",
        Search_Index : @"GET"};
    });
    return _method;
}

@implementation AFFBaseApi
+ (BOOL)propertyIsOptional:(NSString *)propertyName {
    return YES;
}
+(JSONKeyMapper*)keyMapper{
    return [[JSONKeyMapper alloc] initWithDictionary:@{@"id":@"mapToid",@"try":@"mapTotry",@"delete":@"mapTodelete",@"template":@"mapTotemplate",@"let":@"mapTolet",@"interface":@"mapTointerface",@"implementation":@"mapToimplementation",@"protocol":@"mapToprotocol"}];
}
@end
@implementation AFFFindIndex @end
@implementation AFFHomeIndex @end
@implementation AFFSearchIndex @end
@implementation AFFGoodItem @end
@implementation AFFPictureItem @end

