package com.afantree.model.common;

import com.afantree.model.common.PictureItem;


/*
 * 
 * This file was automatically generated by ModelKit. It must not be modified manually!
 */

public class GoodItem {
    /**
     * id
     */
    public int id = 0;
    /**
     * 
     */
    public String intro = "";
    /**
     * 
     */
    public PictureItem picture = new PictureItem();
    /**
     * 问题标题/标题字段
     */
    public String title = "";

}


