package com.afantree.model.common;


/*
 * 
 * This file was automatically generated by ModelKit. It must not be modified manually!
 */

public class PictureItem {
    /**
     * 
     */
    public int height = 0;
    /**
     * 
     */
    public String url = "";
    /**
     * 
     */
    public int width = 0;

}


