package com.afantree.model.common;
import java.net.URLEncoder;
import java.io.UnsupportedEncodingException;

/*
 * Utils
 * This file was automatically generated by ModelKit. It must not be modified manually!
 */

public class Utils {
    public static final String encode(String content) {
        try {
            return content == null ? null : URLEncoder.encode(content, "UTF-8");
        } catch (UnsupportedEncodingException e) {
            throw new RuntimeException(e);
        }
    }
}

